name: 'Setup Emscripten toolchain'
description: 'Download emsdk and optionally install a version of Emscripten'
author: 'mymindstorm'
inputs:
  version:
    description: 'Version to install'
    default: 'latest'
  no-install:
    description: "If true will not download any version of Emscripten. emsdk will still be added to PATH."
    default: false
  no-cache:
    description: "If true will not cache any downloads with tc.cacheDir."
    default: false
  actions-cache-folder:
    description: "Set to the folder where your cached emsdk-master folder is or where emsdk cache will be copied to on sucessful run. This folder will go under $GITHUB_HOME (I.e. build dir)."
    default: ''
  update-tags:
    description: "Update tags before installing a version"
    default: false
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'download'
  color: 'green'
